check grep status

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -157,14 +157,12 @@ jobs:
             cp /usr/bin/qemu-arm-static .
             cp /usr/bin/qemu-aarch64-static .
             cp target/$TARGET/debug/rmate .
-            ldd ./rmate || echo
-            file ./rmate || echo
+            file ./rmate
             docker build -f Dockerfile-<< parameters.target >> -t 'arm_rust:testing' .
-            echo "\nRunning rmate binary for << parameters.target >>\n"
+            # echo "Running rmate binary for << parameters.target >>"
             docker run --rm 'arm_rust:testing' 2>output.log || echo
-            cat output.log
-            grep "Error: \"Connection refused (os error" ./output.log || echo
-            echo $?
+            # cat output.log
+            grep "Error: \"Connection refused (os error" ./output.log || echo "code is " $?
 
   macosimage:
     parameters:
