Try to capture output of rmate run

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -161,7 +161,10 @@ jobs:
             file ./rmate || echo
             docker build -f Dockerfile-<< parameters.target >> -t 'arm_rust:testing' .
             echo "\nRunning rmate binary for << parameters.target >>\n"
-            docker run --rm 'arm_rust:testing'
+            docker run --rm 'arm_rust:testing' 2>&1 > output.log
+            cat output.log
+            grep "Error: \"Connection refused (os error" ./output.log
+            echo $?
 
   macosimage:
     parameters:
